workspace:
  base: /go
  path: src/github.com/go-pluto/maildir_exporter

pipeline:
  build:
    image: golang:1.9
    commands:
    - make all
    when:
      event: [ push, tag ]

  docker:
    image: plugins/docker
    repo: gopluto/maildir_exporter
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push
